# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Publish TypeDoc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - run: yarn add -D typedoc

      - name: Build TypeDoc
        run: yarn typedoc src/embedded.ts

      - name: Publish TypeDoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
